// car.http
@token = TU_TOKEN_AQUI
@baseUrl = http://localhost:3000

### ========== PUBLIC ==========

### List cars (PUBLIC)
GET {{baseUrl}}/api/car/public

### Get car by ID (PUBLIC)
GET {{baseUrl}}/api/car/public/10

### Create car (PUBLIC)
POST {{baseUrl}}/api/car/public
Content-Type: application/json

{
  "brand": "Toyota",
  "class": "SUV",
  "model": "2025",
  "displacement": 2000,
  "capacity": 4,
  "status": "ACTIVE"
}

### Update car (PUBLIC)
PATCH {{baseUrl}}/api/car/public/11
Content-Type: application/json

{
  "brand": "Mazda",
  "class": "Sedan",
  "model": "2023",
  "displacement": 1900,
  "capacity": 5,
  "status": "ACTIVE"
}

### Hard delete car (PUBLIC)
DELETE {{baseUrl}}/api/car/public/16

### Soft delete car (PUBLIC)
DELETE {{baseUrl}}/api/car/public/18/logic